// Code generated by protoc-gen-go.
// source: hello.proto
// DO NOT EDIT!

/*
Package hello is a generated protocol buffer package.

It is generated from these files:
	hello.proto

It has these top-level messages:
	HealthResponse
	Count
	CountsResponse
	SayHiRequest
	SayHiResponse
*/
package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/grpc-ecosystem/grpc-gateway/third_party/googleapis/google/api"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// HealthRsponse contains the service health stats.
type HealthResponse struct {
}

func (m *HealthResponse) Reset()                    { *m = HealthResponse{} }
func (m *HealthResponse) String() string            { return proto.CompactTextString(m) }
func (*HealthResponse) ProtoMessage()               {}
func (*HealthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Count struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Count uint64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *Count) Reset()                    { *m = Count{} }
func (m *Count) String() string            { return proto.CompactTextString(m) }
func (*Count) ProtoMessage()               {}
func (*Count) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Count) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Count) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// CountsResponse contains a list of
type CountsResponse struct {
	Counts []*Count `protobuf:"bytes,1,rep,name=counts" json:"counts,omitempty"`
}

func (m *CountsResponse) Reset()                    { *m = CountsResponse{} }
func (m *CountsResponse) String() string            { return proto.CompactTextString(m) }
func (*CountsResponse) ProtoMessage()               {}
func (*CountsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *CountsResponse) GetCounts() []*Count {
	if m != nil {
		return m.Counts
	}
	return nil
}

// SayHiRequest contains the name of the person to send the greeting to.
type SayHiRequest struct {
	// Name is the name of the person to greet.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SayHiRequest) Reset()                    { *m = SayHiRequest{} }
func (m *SayHiRequest) String() string            { return proto.CompactTextString(m) }
func (*SayHiRequest) ProtoMessage()               {}
func (*SayHiRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SayHiRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// SayHiResponse returns a greeting message.
type SayHiResponse struct {
	// Greeting is the actual message.
	Greeting string `protobuf:"bytes,1,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *SayHiResponse) Reset()                    { *m = SayHiResponse{} }
func (m *SayHiResponse) String() string            { return proto.CompactTextString(m) }
func (*SayHiResponse) ProtoMessage()               {}
func (*SayHiResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SayHiResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

func init() {
	proto.RegisterType((*HealthResponse)(nil), "hello.HealthResponse")
	proto.RegisterType((*Count)(nil), "hello.Count")
	proto.RegisterType((*CountsResponse)(nil), "hello.CountsResponse")
	proto.RegisterType((*SayHiRequest)(nil), "hello.SayHiRequest")
	proto.RegisterType((*SayHiResponse)(nil), "hello.SayHiResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hello service

type HelloClient interface {
	// SayHi greets a given name.
	SayHi(ctx context.Context, in *SayHiRequest, opts ...grpc.CallOption) (*SayHiResponse, error)
	// Health reports service health status.
	Health(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*HealthResponse, error)
	Counts(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*CountsResponse, error)
	DeleteCounts(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHi(ctx context.Context, in *SayHiRequest, opts ...grpc.CallOption) (*SayHiResponse, error) {
	out := new(SayHiResponse)
	err := grpc.Invoke(ctx, "/hello.Hello/SayHi", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) Health(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	out := new(HealthResponse)
	err := grpc.Invoke(ctx, "/hello.Hello/Health", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) Counts(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*CountsResponse, error) {
	out := new(CountsResponse)
	err := grpc.Invoke(ctx, "/hello.Hello/Counts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) DeleteCounts(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/hello.Hello/DeleteCounts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service

type HelloServer interface {
	// SayHi greets a given name.
	SayHi(context.Context, *SayHiRequest) (*SayHiResponse, error)
	// Health reports service health status.
	Health(context.Context, *google_protobuf1.Empty) (*HealthResponse, error)
	Counts(context.Context, *google_protobuf1.Empty) (*CountsResponse, error)
	DeleteCounts(context.Context, *google_protobuf1.Empty) (*google_protobuf1.Empty, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Hello/SayHi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHi(ctx, req.(*SayHiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Hello/Health",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Health(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_Counts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Counts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Hello/Counts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Counts(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_DeleteCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).DeleteCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Hello/DeleteCounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).DeleteCounts(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHi",
			Handler:    _Hello_SayHi_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _Hello_Health_Handler,
		},
		{
			MethodName: "Counts",
			Handler:    _Hello_Counts_Handler,
		},
		{
			MethodName: "DeleteCounts",
			Handler:    _Hello_DeleteCounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 331 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0xc1, 0x4a, 0xf3, 0x40,
	0x14, 0x85, 0x49, 0xff, 0x26, 0xbf, 0xbd, 0xad, 0xad, 0x5e, 0xab, 0x96, 0xe8, 0xa2, 0x04, 0x17,
	0xa5, 0x42, 0x82, 0x15, 0xdc, 0xb9, 0x52, 0x21, 0xe0, 0x42, 0x88, 0x4f, 0x30, 0x95, 0x6b, 0x1a,
	0x48, 0x67, 0x62, 0x67, 0xb2, 0x28, 0xe2, 0xc6, 0x57, 0xf0, 0x69, 0x7c, 0x0e, 0x5f, 0xc1, 0x07,
	0x91, 0xcc, 0x4c, 0xa4, 0x15, 0xa5, 0xbb, 0xdc, 0x39, 0xe7, 0x7e, 0xe7, 0xe6, 0x40, 0x7b, 0x46,
	0x79, 0x2e, 0xc2, 0x62, 0x21, 0x94, 0x40, 0x57, 0x0f, 0xfe, 0x71, 0x2a, 0x44, 0x9a, 0x53, 0xc4,
	0x8a, 0x2c, 0x62, 0x9c, 0x0b, 0xc5, 0x54, 0x26, 0xb8, 0x34, 0x26, 0xff, 0xc8, 0xaa, 0x7a, 0x9a,
	0x96, 0x8f, 0x11, 0xcd, 0x0b, 0xb5, 0x34, 0x62, 0xb0, 0x03, 0xdd, 0x98, 0x58, 0xae, 0x66, 0x09,
	0xc9, 0x42, 0x70, 0x49, 0xc1, 0x19, 0xb8, 0x57, 0xa2, 0xe4, 0x0a, 0x11, 0x9a, 0x9c, 0xcd, 0x69,
	0xe0, 0x0c, 0x9d, 0x51, 0x2b, 0xd1, 0xdf, 0xd8, 0x07, 0xf7, 0xa1, 0x12, 0x07, 0x8d, 0xa1, 0x33,
	0x6a, 0x26, 0x66, 0x08, 0x2e, 0xa0, 0xab, 0x57, 0x64, 0x0d, 0xc1, 0x13, 0xf0, 0xb4, 0x24, 0x07,
	0xce, 0xf0, 0xdf, 0xa8, 0x3d, 0xe9, 0x84, 0xe6, 0x6c, 0x6d, 0x4b, 0xac, 0x16, 0x04, 0xd0, 0xb9,
	0x67, 0xcb, 0x38, 0x4b, 0xe8, 0xa9, 0x24, 0xf9, 0x6b, 0x62, 0x70, 0x0a, 0xdb, 0xd6, 0x63, 0xd1,
	0x3e, 0x6c, 0xa5, 0x0b, 0x22, 0x95, 0xf1, 0xd4, 0x1a, 0xbf, 0xe7, 0xc9, 0x7b, 0x03, 0xdc, 0xb8,
	0x0a, 0xc2, 0x5b, 0x70, 0xf5, 0x1a, 0xee, 0xd9, 0xe4, 0xd5, 0x20, 0xbf, 0xbf, 0xfe, 0x68, 0xff,
	0xfc, 0xf0, 0xf5, 0xe3, 0xf3, 0xad, 0xb1, 0x8b, 0xbd, 0x48, 0xab, 0xd1, 0x73, 0x75, 0xc0, 0xe5,
	0xf8, 0x05, 0x63, 0xf0, 0x4c, 0x49, 0x78, 0x10, 0x9a, 0x32, 0xc3, 0xba, 0xcc, 0xf0, 0xa6, 0x2a,
	0xd3, 0xdf, 0xb7, 0xc0, 0x1f, 0x5d, 0xf6, 0x34, 0xb1, 0x85, 0xff, 0xa3, 0x99, 0xd9, 0x8f, 0xc1,
	0x33, 0x4d, 0x6d, 0x24, 0xad, 0x17, 0xba, 0x42, 0x32, 0xdd, 0xe1, 0x1d, 0x74, 0xae, 0x29, 0x27,
	0x45, 0x1b, 0x78, 0x7f, 0xbc, 0xd7, 0xc0, 0x71, 0x0d, 0x9c, 0x7a, 0xda, 0x70, 0xfe, 0x15, 0x00,
	0x00, 0xff, 0xff, 0xe6, 0x27, 0x52, 0x01, 0x61, 0x02, 0x00, 0x00,
}
