// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello.proto

/*
Package hello is a generated protocol buffer package.

It is generated from these files:
	hello.proto

It has these top-level messages:
	Count
	CountsResponse
	SayHiRequest
	SayHiResponse
	Error
*/
package hello

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Count contains the visitor name and her number of visits.
type Count struct {
	Name  string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Count uint64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
}

func (m *Count) Reset()                    { *m = Count{} }
func (m *Count) String() string            { return proto.CompactTextString(m) }
func (*Count) ProtoMessage()               {}
func (*Count) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Count) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Count) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

// CountsResponse contains a list of visitors and visits.
type CountsResponse struct {
	Counts []*Count `protobuf:"bytes,1,rep,name=counts" json:"counts,omitempty"`
}

func (m *CountsResponse) Reset()                    { *m = CountsResponse{} }
func (m *CountsResponse) String() string            { return proto.CompactTextString(m) }
func (*CountsResponse) ProtoMessage()               {}
func (*CountsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CountsResponse) GetCounts() []*Count {
	if m != nil {
		return m.Counts
	}
	return nil
}

// SayHiRequest contains the name of the person to send the greeting to.
type SayHiRequest struct {
	// Name is the name of the person to greet.
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *SayHiRequest) Reset()                    { *m = SayHiRequest{} }
func (m *SayHiRequest) String() string            { return proto.CompactTextString(m) }
func (*SayHiRequest) ProtoMessage()               {}
func (*SayHiRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SayHiRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// SayHiResponse returns a greeting message.
type SayHiResponse struct {
	// Greeting is the actual message.
	Greeting string `protobuf:"bytes,1,opt,name=greeting" json:"greeting,omitempty"`
}

func (m *SayHiResponse) Reset()                    { *m = SayHiResponse{} }
func (m *SayHiResponse) String() string            { return proto.CompactTextString(m) }
func (*SayHiResponse) ProtoMessage()               {}
func (*SayHiResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SayHiResponse) GetGreeting() string {
	if m != nil {
		return m.Greeting
	}
	return ""
}

// Error returns API error details
type Error struct {
	Code    string `protobuf:"bytes,1,opt,name=code" json:"code,omitempty"`
	Message string `protobuf:"bytes,2,opt,name=message" json:"message,omitempty"`
	Status  uint32 `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`
	Details string `protobuf:"bytes,4,opt,name=details" json:"details,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Error) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetStatus() uint32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *Error) GetDetails() string {
	if m != nil {
		return m.Details
	}
	return ""
}

func init() {
	proto.RegisterType((*Count)(nil), "hello.Count")
	proto.RegisterType((*CountsResponse)(nil), "hello.CountsResponse")
	proto.RegisterType((*SayHiRequest)(nil), "hello.SayHiRequest")
	proto.RegisterType((*SayHiResponse)(nil), "hello.SayHiResponse")
	proto.RegisterType((*Error)(nil), "hello.Error")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Hello service

type HelloClient interface {
	// SayHi greets a given name and records her visit.
	SayHi(ctx context.Context, in *SayHiRequest, opts ...grpc.CallOption) (*SayHiResponse, error)
	// Counts returns the number of visitors recorded.
	Counts(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*CountsResponse, error)
	// DeleteCounts resets the in-memory map that keeps track of visitors and number of visits.
	DeleteCounts(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type helloClient struct {
	cc *grpc.ClientConn
}

func NewHelloClient(cc *grpc.ClientConn) HelloClient {
	return &helloClient{cc}
}

func (c *helloClient) SayHi(ctx context.Context, in *SayHiRequest, opts ...grpc.CallOption) (*SayHiResponse, error) {
	out := new(SayHiResponse)
	err := grpc.Invoke(ctx, "/hello.Hello/SayHi", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) Counts(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*CountsResponse, error) {
	out := new(CountsResponse)
	err := grpc.Invoke(ctx, "/hello.Hello/Counts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *helloClient) DeleteCounts(ctx context.Context, in *google_protobuf1.Empty, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/hello.Hello/DeleteCounts", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Hello service

type HelloServer interface {
	// SayHi greets a given name and records her visit.
	SayHi(context.Context, *SayHiRequest) (*SayHiResponse, error)
	// Counts returns the number of visitors recorded.
	Counts(context.Context, *google_protobuf1.Empty) (*CountsResponse, error)
	// DeleteCounts resets the in-memory map that keeps track of visitors and number of visits.
	DeleteCounts(context.Context, *google_protobuf1.Empty) (*google_protobuf1.Empty, error)
}

func RegisterHelloServer(s *grpc.Server, srv HelloServer) {
	s.RegisterService(&_Hello_serviceDesc, srv)
}

func _Hello_SayHi_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SayHiRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).SayHi(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Hello/SayHi",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).SayHi(ctx, req.(*SayHiRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_Counts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).Counts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Hello/Counts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).Counts(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Hello_DeleteCounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(google_protobuf1.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HelloServer).DeleteCounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Hello/DeleteCounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HelloServer).DeleteCounts(ctx, req.(*google_protobuf1.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Hello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Hello",
	HandlerType: (*HelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHi",
			Handler:    _Hello_SayHi_Handler,
		},
		{
			MethodName: "Counts",
			Handler:    _Hello_Counts_Handler,
		},
		{
			MethodName: "DeleteCounts",
			Handler:    _Hello_DeleteCounts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello.proto",
}

func init() { proto.RegisterFile("hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 364 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x51, 0xc1, 0x4a, 0xeb, 0x40,
	0x14, 0x25, 0x6d, 0x93, 0xbe, 0xde, 0xb6, 0xaf, 0xbc, 0x79, 0xb5, 0x86, 0xe8, 0x22, 0x0c, 0x2e,
	0x42, 0x85, 0x04, 0x2b, 0xb8, 0x73, 0xa5, 0x85, 0x82, 0x0b, 0x21, 0x7e, 0xc1, 0xb4, 0xbd, 0xc6,
	0x40, 0x9a, 0x89, 0x99, 0xc9, 0xa2, 0x88, 0x1b, 0x7f, 0xc1, 0x4f, 0xf3, 0x17, 0xdc, 0xfb, 0x0b,
	0x92, 0x99, 0x49, 0xa9, 0xa0, 0xb8, 0x9b, 0x73, 0xcf, 0xb9, 0x67, 0xee, 0xb9, 0x17, 0xfa, 0x0f,
	0x98, 0x65, 0x3c, 0x2c, 0x4a, 0x2e, 0x39, 0xb1, 0x15, 0xf0, 0x8e, 0x13, 0xce, 0x93, 0x0c, 0x23,
	0x56, 0xa4, 0x11, 0xcb, 0x73, 0x2e, 0x99, 0x4c, 0x79, 0x2e, 0xb4, 0xc8, 0x3b, 0x32, 0xac, 0x42,
	0xcb, 0xea, 0x3e, 0xc2, 0x4d, 0x21, 0xb7, 0x9a, 0xa4, 0x67, 0x60, 0x5f, 0xf1, 0x2a, 0x97, 0x84,
	0x40, 0x27, 0x67, 0x1b, 0x74, 0x2d, 0xdf, 0x0a, 0x7a, 0xb1, 0x7a, 0x93, 0x31, 0xd8, 0xab, 0x9a,
	0x74, 0x5b, 0xbe, 0x15, 0x74, 0x62, 0x0d, 0xe8, 0x05, 0xfc, 0x55, 0x2d, 0x22, 0x46, 0x51, 0xf0,
	0x5c, 0x20, 0x39, 0x01, 0x47, 0x51, 0xc2, 0xb5, 0xfc, 0x76, 0xd0, 0x9f, 0x0d, 0x42, 0x3d, 0xa4,
	0x92, 0xc5, 0x86, 0xa3, 0x14, 0x06, 0x77, 0x6c, 0xbb, 0x48, 0x63, 0x7c, 0xac, 0x50, 0x7c, 0xfb,
	0x23, 0x3d, 0x85, 0xa1, 0xd1, 0x18, 0x6b, 0x0f, 0xfe, 0x24, 0x25, 0xa2, 0x4c, 0xf3, 0xc4, 0x08,
	0x77, 0x98, 0x26, 0x60, 0xcf, 0xcb, 0x92, 0x97, 0xb5, 0xd3, 0x8a, 0xaf, 0x77, 0x4e, 0xf5, 0x9b,
	0xb8, 0xd0, 0xdd, 0xa0, 0x10, 0x2c, 0x41, 0x35, 0x7d, 0x2f, 0x6e, 0x20, 0x99, 0x80, 0x23, 0x24,
	0x93, 0x95, 0x70, 0xdb, 0xbe, 0x15, 0x0c, 0x63, 0x83, 0xea, 0x8e, 0x35, 0x4a, 0x96, 0x66, 0xc2,
	0xed, 0xe8, 0x0e, 0x03, 0x67, 0x1f, 0x16, 0xd8, 0x8b, 0x3a, 0x11, 0xb9, 0x01, 0x5b, 0xcd, 0x47,
	0xfe, 0x9b, 0x88, 0xfb, 0x89, 0xbc, 0xf1, 0xd7, 0xa2, 0x8e, 0x40, 0x0f, 0x5f, 0xde, 0xde, 0x5f,
	0x5b, 0xff, 0xc8, 0x28, 0x52, 0x6c, 0xf4, 0x54, 0x27, 0xbd, 0x9c, 0x3e, 0x93, 0x05, 0x38, 0x7a,
	0x91, 0x64, 0x12, 0xea, 0x1b, 0x85, 0xcd, 0x8d, 0xc2, 0x79, 0x7d, 0x23, 0xef, 0x60, 0x7f, 0x91,
	0xbb, 0x7d, 0xd3, 0x91, 0x72, 0xec, 0x91, 0x6e, 0xa4, 0x57, 0x4b, 0x6e, 0x61, 0x70, 0x8d, 0x19,
	0x4a, 0xfc, 0xc5, 0xef, 0x87, 0x7a, 0x63, 0x38, 0x6d, 0x0c, 0x97, 0x8e, 0x12, 0x9c, 0x7f, 0x06,
	0x00, 0x00, 0xff, 0xff, 0xe9, 0x98, 0x9f, 0x12, 0x6e, 0x02, 0x00, 0x00,
}
