apiVersion: v1
kind: Service
metadata:
  name: hello
  labels:
    app: hello
spec:
  type: LoadBalancer
  ports:
  - port: 443
    name: https
    targetPort: 9999
    protocol: TCP
  - port: 80
    name: http
    targetPort: 9998
    protocol: TCP
  selector:
    app: hello
